FROM python:3.12.3-slim-bookworm

ARG SERVICE

COPY --from=ghcr.io/astral-sh/uv:0.9.0 /uv /bin/uv

WORKDIR /app

COPY services/python/${SERVICE} .
# COPY shared-code/python /shared-code/python

ENV UV_SYSTEM_PYTHON=1

RUN uv pip install -r pyproject.toml

CMD ["python", "src/main.py"]