FROM python:3.12.3-slim-bookworm

ARG SERVICE

COPY --from=ghcr.io/astral-sh/uv:0.11.18 /uv /bin/uv

WORKDIR /app

COPY services/python/${SERVICE} /app
COPY shared-code/python/app/pyproject.toml /shared-code/python/app/pyproject.toml
COPY shared-code/python/app/src /shared-code/python/app/src

ENV UV_SYSTEM_PYTHON=1

RUN uv pip install --no-cache --no-sources \
    -r /app/pyproject.toml \
    /shared-code/python/app

CMD ["python", "/app/src/main.py"]