{
 "title": "Method Latency (P50, P90, P99)",
 "description": "Latency of each CRUD method aggregated into percentiles",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "POST P50 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "POST P90 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "POST P99 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PUT P50 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PUT P90 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PUT P99 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PATCH P50 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PATCH P90 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "PATCH P99 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "GET P50 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "GET P90 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "GET P99 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "DELETE P50 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "DELETE P90 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "DELETE P99 Latency",
   "type": "timeseries",
   "description": "1 method per provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}