{
 "title": "Provider Specifics",
 "description": "Display information specific to 1 selected provider at a time",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "provider", "label": "provider", "query": "axum,actix" }
  ]
 },
 "panels": [
  {
   "title": "Operations in RAM by Provider",
   "type": "timeseries",
   "description": "Breakdown of the number of operations the generator has in its memory at each moment",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (operation) (live_operations{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Sent by Method",
   "type": "timeseries",
   "description": "Number of requests aggregated by method",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (requests{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests Sent by Operation",
   "type": "timeseries",
   "description": "Number of requests aggregated by operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (operation) (requests{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations in RAM by Provider",
   "type": "piechart",
   "description": "Distribution of operations in the generators memory at this moment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (live_operations{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Sent by Method",
   "type": "piechart",
   "description": "Distribution of requests sent by the generator",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (requests{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Sent by Operation",
   "type": "piechart",
   "description": "Distribution of requests sent by the generator",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (requests{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Method Latency",
   "type": "timeseries",
   "description": "Latency per method at a specific instant in time across all operations",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (method) (latency{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Latency",
   "type": "timeseries",
   "description": "Latency per operation at a specific instant in time across all methods",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (operation) (latency{job=\"generator\", provider=\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", method=\"POST\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", method=\"PUT\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATCH Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATCH Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", method=\"PATCH\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", method=\"GET\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", method=\"DELETE\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", operation=\"compute\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", operation=\"compute\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sort Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", operation=\"sort\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sort Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", operation=\"sort\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", operation=\"merge\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", operation=\"merge\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transform Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum by (le) (rate(latency_percentile_bucket{job=\"generator\", operation=\"transform\", provider=\"$provider\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transform Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum by (le) (increase(latency_percentile_bucket{job=\"generator\", operation=\"transform\", provider=\"$provider\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}