{
 "title": "Provider Latency",
 "description": "Aggregations of latencies across all providers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P50 Providers",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "P90 Providers",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "P99 Providers",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (provider, language, le) (rate(latency_percentile_bucket{job=\"generator\", method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Provider P50 Latency",
   "type": "timeseries",
   "description": "Combine all methods for each provider to get an overall latency",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Provider P90 Latency",
   "type": "timeseries",
   "description": "Combine all methods for each provider to get an overall latency",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Provider P99 Latency",
   "type": "timeseries",
   "description": "Combine all methods for each provider to get an overall latency",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (provider, le) (rate(latency_percentile_bucket{job=\"generator\"}[$__rate_interval])))",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}