{
 "title": "Randomiser",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Distribution",
   "type": "logs",
   "description": "Requests are randomised periodically. This panel shows the method distribution",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"(?P<x>Randomised requests)\"\n| line_format \"{{ __line__ }} | POST={{.post}}% | GET={{.get}}% | PUT={{.put}}% | PATCH={{.patch}}% | DELETE={{.delete}}% | HEAD={{.head}}% | TOTAL={{.total}}\""
    }
   ]
  },
  {
   "title": "Operation Distribution",
   "type": "logs",
   "description": "Operations are randomised periodically. This panel shows the operation distribution",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"(?P<x>Randomised operations)\"\n| line_format \"{{ __line__ }} | COMPUTE={{.compute}}% | SORT={{.sort}}% | TRANSFORM={{.transform}}% | MERGE={{.merge}}% | TOTAL={{.total}}\""
    }
   ]
  },
  {
   "title": "Request %",
   "type": "timeseries",
   "description": "Probability of a method being called over time",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"Randomised requests\""
    }
   ]
  },
  {
   "title": "Operation %",
   "type": "timeseries",
   "description": "Probability of a operation being created over time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"Randomised operations\""
    }
   ]
  },
  {
   "title": "Total Request Fill",
   "type": "timeseries",
   "description": "Probability starts with a number of tokens to distribute across methods. This is the total number of tokens consumed/filled",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"Randomised requests\""
    }
   ]
  },
  {
   "title": "Total Operation Fill",
   "type": "timeseries",
   "description": "Probability starts with a number of tokens to distribute across operations. This is the total number of tokens consumed/filled",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n|~ \"Randomised operations\""
    }
   ]
  }
 ]
}