{
 "title": "System Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "method", "label": "method", "query": { "query": "label_values(method)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "provider", "label": "provider", "query": { "query": "label_values(provider)" } },
   { "name": "level", "label": "level", "query": "info,warn,debug,error" },
   { "name": "id", "label": "id" }
  ]
 },
 "panels": [
  {
   "title": "Warn/Errors",
   "type": "timeseries",
   "description": "Change the provider to see the number of warnings/errors for that provider or leave it as \"All\" to see all warnings/errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\n  count_over_time(\n    {service_name=\"generator\"}\n    | detected_level=~\"(?i)(warn|error)\"\n    [$__auto]\n  )\n)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Warn/Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (line, detected_level) (\n  count_over_time(\n    {service_name=\"generator\"}\n    | detected_level=~\"(?i)(warn|error)\"\n    | label_format line=\"{{ __line__ }}\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n| method=~\"(?i)$method\"\n| operation=~\"(?i)$operation\" or to_operation=~\"(?i)$operation\"\n| provider=~\"(?i)$provider\"\n| detected_level=~\"(?i)warn\"\n| id=~\"(?i)$id\"\n| line_format \"| {{ if .error }}{{ .error }}{{ end }} | {{ if .method }}{{ .method }}{{ end }}{{ if .provider }} | {{ .provider }}{{ end }}{{ if .operation }} | {{ .operation }}{{ else if .to_operation }} | {{ .to_operation }}{{ end }}{{ if .id }} | {{ .id }}{{ end }} | {{ if .secret }}{{ .secret }}{{ end }}\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n| method=~\"(?i)$method\"\n| operation=~\"(?i)$operation\" or to_operation=~\"(?i)$operation\"\n| provider=~\"(?i)$provider\"\n| detected_level=~\"(?i)error\"\n| id=~\"(?i)$id\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n| method=~\"(?i)$method\"\n| operation=~\"(?i)$operation\" or to_operation=~\"(?i)$operation\"\n| provider=~\"(?i)$provider\"\n| detected_level=~\"(?i)$level\"\n| id=~\"(?i)$id\"\n| line_format \"{{ if .method }}{{ .method }}{{ else }}{{ __line__ }}{{ end }}{{ if .provider }} | {{ .provider }}{{ end }}{{ if .operation }} | {{ .operation }}{{ else if .to_operation }} | {{ .to_operation }}{{ end }}{{ if .id }} | {{ .id }}{{ end }}\""
    }
   ]
  }
 ]
}