{
 "title": "Generator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "method", "label": "method", "query": "POST,GET,PATCH,PUT,DELETE" },
   { "name": "operation", "label": "operation", "query": "COMPUTE,MERGE,SORT,TRANSFORM" },
   { "name": "id", "label": "id" }
  ]
 },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency{job=\"generator\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "stat",
   "description": "How long it takes the worker to send a request to the api and receive a response.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "instant",
     "query": "{ resource.service.name=\"generator\" && span:name=\"send\" }\n| quantile_over_time(span:duration, 0.50) by (span.method)",
     "spss": 1,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "description": "How long it takes the worker to send a request to the api and receive a response.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "instant",
     "query": "{ resource.service.name=\"generator\" && span:name=\"send\" }\n| quantile_over_time(span:duration, 0.95) by (span.method)",
     "spss": 1,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "stat",
   "description": "How long it takes the worker to send a request to the api and receive a response.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "instant",
     "query": "{ resource.service.name=\"generator\" && span:name=\"send\" }\n| quantile_over_time(span:duration, 0.99) by (span.method)",
     "spss": 1,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Operations in RAM",
   "type": "timeseries",
   "description": "Breakdown of the number of operations the generator has in its memory at each moment",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "live_operations{job=\"generator\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Historical Requests Sent",
   "type": "timeseries",
   "description": "Number of requests, by method, sent to the servers",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "requests{job=\"generator\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Historical Operations Sent",
   "type": "timeseries",
   "description": "Breakdown of the number of operations the generator has generated over its history",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "total_operations{job=\"generator\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Operations in RAM",
   "type": "piechart",
   "description": "Distribution of operations in the generators memory at this moment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "live_operations{job=\"generator\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Historical Requests Sent",
   "type": "piechart",
   "description": "Distribution of requests sent by the generator",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests{job=\"generator\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Historical Operations Sent",
   "type": "piechart",
   "description": "Distribution of operations the generator has made in its history",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_operations{job=\"generator\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Slowest Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "filters": [
      { "id": "46cac3d8", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "generator" ],
       "valueType": "string"
      }
     ],
     "limit": 200,
     "metricsQueryType": "range",
     "query": "{ resource.service.name=\"generator\" && name = trace:rootName }",
     "spss": 1,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"generator\"}\n| method=~\"(?i)$method\"\n| operation=~\"(?i)$operation\"\n| id=~\"(?i)$id\"\n| line_format \"{{ __line__ }}{{ if .id }} | id={{ .id }}{{ end }}\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time spent running the service",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "labelSelector": "{service_name=\"generator\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "flamegraph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "labelSelector": "{service_name=\"generator\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  }
 ]
}