{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Generator: Client Requests",
   "type": "timeseries",
   "description": "Number of requests, by method, sent to the servers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "requests", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Generator: Client Requests",
   "type": "piechart",
   "description": "Distribution of requests sent by the generator",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Generator: Live Operations",
   "type": "timeseries",
   "description": "Breakdown of the number of operations the generator has in its memory at each moment",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "live_operations", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Generator: Live Operations",
   "type": "piechart",
   "description": "Distribution of operations in the generators memory at this moment",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "live_operations", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Generator: Total Operations",
   "type": "timeseries",
   "description": "Breakdown of the number of operations the generator has generated over its history",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "total_operations", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Generator: Total Operations",
   "type": "piechart",
   "description": "Distribution of operations the generator has made in its history",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_operations", "legendFormat": "{{operation}}" }
   ]
  }
 ]
}