{
 "title": "Web Frameworks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "method", "label": "method", "query": { "query": "label_values(method)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "provider", "label": "provider", "query": { "query": "label_values(provider)" } },
   { "name": "id", "label": "id" }
  ]
 },
 "panels": [
  {
   "title": "Warn/Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (line, detected_level, error, method, path) (\n  count_over_time(\n    {service_name=\"$provider\"}\n    | detected_level=~\"(?i)(warn|error)\"\n    | label_format line=\"{{ __line__ }}\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$provider\"}\n| method=~\"(?i)$method\"\n| detected_level=~\"(?i)warn\"\n| line_format \"| {{ __line__ }}{{ if .method }} | {{ .method }}{{ end }}{{ if .path }} | {{ .path }}{{ end }}\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$provider\"}\n| method=~\"(?i)$method\"\n| detected_level=~\"(?i)error\"\n| line_format \"| {{ __line__ }}{{ if .method }} | {{ .method }}{{ end }}{{ if .id }} | {{ .id }}{{ end }}\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$provider\"}\n| method=~\"(?i)$method\"\n| operation=~\"(?i)$operation\"\n| id=~\"(?i)$id\"\n| line_format \"| {{ __line__ }}{{ if .method }} | {{ .method }}{{ end }}{{ if .operation }} | {{ .operation }}{{ end }}{{ if .secret }} | {{ .secret }}{{ end }}{{ if .id }} | id={{ .id }}{{ end }}\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time spent running the service",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "labelSelector": "{service_name=\"$provider\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "flamegraph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "labelSelector": "{service_name=\"$provider\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  }
 ]
}